test:
    build: .
    ports:
        - "80:80"
        - "443:443"
        - "1936:1936"
    environment:
      - 'HCM_BACKEND_HCM_CORE=192.168.199.171:8000'
      - 'HCM_BACKEND_HCM_CLOUD=192.168.199.171:8080'
      - 'HCM_URL_1=default:HCM_CLOUD'
      - 'HCM_URL_2=/api:HCM_CORE'
      - 'HCM_URL_3=/login:HCM_CORE'


